version: '3.8'

networks:
  airflow-net:

services:
  airflow:
    image: apache/airflow:3.0.3-python3.10
    container_name: courtsight-airflow
    networks:
      - airflow-net
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/airflow/project
      - ./airflow/dags:/opt/airflow/project/dags
      - ./airflow/plugins:/opt/airflow/project/plugins
    environment:
      AIRFLOW_HOME: /opt/airflow/project
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
    command: >
      bash -c "cd /opt/airflow/project && pip install -r requirements.txt && airflow standalone"

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: courtsight-clickhouse
    networks:
      - airflow-net
    ports:
      - "8123:8123"
      - "5473:5473"
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
